// PROTECTED ACCEPTANCE MATRIX: authored independently of the implementation.
// Do not edit this file to make an implementation pass.

import 'package:flutter_test/flutter_test.dart';
import 'package:navigation_app/services/backup/app_fault.dart';
import 'package:navigation_app/services/backup/backup_controller.dart';
import 'package:navigation_app/services/backup/backup_log.dart';
import 'package:navigation_app/services/backup/backup_revision.dart';
import 'package:navigation_app/services/backup/backup_scheduler.dart';
import 'package:navigation_app/services/backup/backup_service.dart';
import 'package:navigation_app/services/backup/backup_status.dart';
import 'package:navigation_app/services/backup/mock/mock_backup_target.dart';
import 'package:navigation_app/services/config_bundle.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:shared_preferences_platform_interface/shared_preferences_platform_interface.dart';

const _targetIdentity = 'mock:test';

const _hardKinds = <BackupFailureKind>[
  BackupFailureKind.offline,
  BackupFailureKind.authExpired,
  BackupFailureKind.storageFull,
  BackupFailureKind.targetMissing,
];

const _questionOutcomes = <PullOutcome>[
  PullOutcome.conflict,
  PullOutcome.needsAdoptionChoice,
];

AppFault _hardFault(BackupFailureKind kind, {required String operation}) =>
    AppFault.backup(
      kind,
      'Injected ${kind.name} failure.',
      operation: operation,
      targetIdentity: _targetIdentity,
    );

BackupRevision _revision(String id) => BackupRevision(
      id: id,
      filename: '$id.json',
      createdAt: DateTime.utc(2026, 8, 16, 9),
      contentHash: 'content-$id',
      bodyChecksum: 'body-$id',
      parentRevisionId: null,
      sizeBytes: 1,
      deviceLabel: 'Other Mac',
    );

PullResult _question(PullOutcome outcome, BackupRevision revision) =>
    PullResult(outcome, revision: revision);

/// Holds only the first log persistence long enough for a non-serialized fold
/// to let later events finish ahead of it.
class _DelayedFirstLogWriteStore extends InMemorySharedPreferencesStore {
  _DelayedFirstLogWriteStore() : super.withData({});

  var _delayed = false;

  @override
  Future<bool> setValue(String valueType, String key, Object value) async {
    if (key == 'flutter.${BackupLog.key}' && !_delayed) {
      _delayed = true;
      await Future<void>.delayed(const Duration(milliseconds: 25));
    }
    return super.setValue(valueType, key, value);
  }
}

Future<void> _waitForUnknown(BackupController controller) async {
  for (var attempt = 0; attempt < 100; attempt++) {
    if (controller.status.value.activeCondition?.kind ==
        BackupFailureKind.unknown.name) {
      return;
    }
    await Future<void>.delayed(const Duration(milliseconds: 1));
  }
  fail('The queued fold did not report its exception as an unknown fault.');
}

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  late DateTime clock;
  late MockBackupTarget target;
  late BackupService service;
  late BackupLog log;
  late BackupController controller;

  setUp(() {
    SharedPreferences.setMockInitialValues({});
    clock = DateTime.utc(2026, 8, 16, 9);
    target = MockBackupTarget();
    service = BackupService(
      target: target,
      targetIdentity: _targetIdentity,
      deviceLabel: () async => 'Mac mini',
      readBundleJson: () async => (await ConfigBundle.fromStores()).toJson(),
      localIsPristine: ConfigBundle.localIsPristine,
    );
    log = BackupLog(now: () => clock);
    controller = BackupController.forService(
      service,
      scheduler: BackupScheduler(
        service: service,
        debounce: const Duration(milliseconds: 1),
        sweepInterval: const Duration(days: 1),
        sleep: (_) async {},
      ),
      log: log,
      now: () => clock,
    );
  });

  tearDown(() => controller.dispose());

  group('hard failures outrank every unresolved question in either order', () {
    for (final hardKind in _hardKinds) {
      for (final questionOutcome in _questionOutcomes) {
        final questionName = questionOutcome == PullOutcome.conflict
            ? 'conflict'
            : 'adoption choice';

        test('${hardKind.name} then $questionName remains failing', () async {
          // The hard fault is deliberately push and the question pull: the
          // pull completion must not erase an unresolved upload failure.
          await controller.handleEvent(_hardFault(hardKind, operation: 'push'));
          await controller.handleEvent(
              _question(questionOutcome, _revision('$questionName-after-hard')));

          expect(controller.status.value.state, BackupPillState.failing,
              reason: 'an amber review prompt must not hide a backup failure '
                  'that still strands this machine\'s local edits');
          expect(controller.status.value.activeCondition!.kind, hardKind.name,
              reason: 'the active red condition must remain the hard failure, '
                  'not whichever event happened last');
        });

        test('$questionName then ${hardKind.name} becomes failing', () async {
          await controller.handleEvent(
              _question(questionOutcome, _revision('$questionName-before-hard')));
          await controller.handleEvent(_hardFault(hardKind, operation: 'push'));

          expect(controller.status.value.state, BackupPillState.failing,
              reason: 'a newly discovered hard failure must interrupt review '
                  'rather than leave the operator with a false amber state');
          expect(controller.status.value.activeCondition!.kind, hardKind.name,
              reason: 'the red condition must be selected by precedence, not '
                  'by a special case for conflict or adoption prompts');
        });
      }
    }
  });

  test('the most recently raised live operation failure shows, then the other survives its completion',
      () async {
    await controller.handleEvent(
        _hardFault(BackupFailureKind.offline, operation: 'push'));
    await controller.handleEvent(
        _hardFault(BackupFailureKind.storageFull, operation: 'pull'));

    expect(controller.status.value.activeCondition!.kind,
        BackupFailureKind.storageFull.name,
        reason: 'when two operations are broken, the newest live failure is '
            'the one the operator needs to see first');
    expect(controller.status.value.activeCondition!.operation, 'pull',
        reason: 'failure state is keyed by operation so one completion cannot '
            'erase another operation\'s fault');

    await controller.handleEvent(const PullResult(PullOutcome.nothingToDo));

    expect(controller.status.value.state, BackupPillState.failing,
        reason: 'a completed pull must not turn green while the upload remains '
            'offline');
    expect(controller.status.value.activeCondition!.kind,
        BackupFailureKind.offline.name,
        reason: 'clearing the pull condition must reveal the still-live push '
            'failure instead of losing it');
    expect(controller.status.value.activeCondition!.operation, 'push',
        reason: 'the surviving condition must still name the operation that '
            'needs recovery');
  });

  test('a question keeps its revision until a real resolution clears it',
      () async {
    final revision = _revision('fork-revision');
    await controller.handleEvent(
        PullResult(PullOutcome.conflict, revision: revision));

    expect(controller.conflictRevision, same(revision),
        reason: 'the resolution dialog must receive the exact remote revision '
            'that created the question');

    await controller.handleEvent(const PullResult(PullOutcome.nothingToDo));

    expect(controller.conflictRevision, same(revision),
        reason: 'nothing-to-do does not resolve a fork, so dropping its '
            'revision would aim the dialog at stale or missing data');

    await controller.handleEvent(const PushResult(PushOutcome.noOp));

    expect(controller.status.value.state, isNot(BackupPillState.needsReview),
        reason: 'a confirmed matching durable copy resolves the question');
    expect(controller.conflictRevision, isNull,
        reason: 'a cleared question must not leave a stale revision available '
            'to a later resolution dialog');
  });

  test('dismissing a log row never dismisses its active pill condition',
      () async {
    await controller.handleEvent(
        _hardFault(BackupFailureKind.authExpired, operation: 'push'));
    final active = controller.status.value.activeCondition!;

    await controller.dismiss(active.fingerprint);

    expect(controller.status.value.state, BackupPillState.failing,
        reason: 'reading a log entry must not pretend credentials recovered');
    expect(controller.status.value.activeCondition!.fingerprint,
        active.fingerprint,
        reason: 'the pill is an authority about the live condition, not the '
            'read/unread state of its history row');
    expect(log.entries.value.single.dismissed, isTrue,
        reason: 'the operator\'s dismissal belongs only to the history row');
  });

  test('a queued fold exception is red and logged, then later work still folds',
      () async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('preset_names_acceptance_corrupt', '{not json');

    controller.handleEventUnserialized(const PushResult(PushOutcome.noOp));
    await _waitForUnknown(controller);

    expect(controller.status.value.state, BackupPillState.failing,
        reason: 'a corrupted local preference must never leave the pill quietly '
            'showing an earlier, confident status');
    expect(controller.status.value.activeCondition!.kind,
        BackupFailureKind.unknown.name,
        reason: 'an exception in the fold must become an operator-visible '
            'unknown backup failure');
    expect(
      log.entries.value,
      anyElement(isA<BackupLogEntry>().having(
          (entry) => entry.kind, 'kind', BackupFailureKind.unknown.name)),
      reason: 'the exception needs a durable diagnostic row, not only a red '
          'pill with no explanation',
    );

    await prefs.remove('preset_names_acceptance_corrupt');
    await controller.handleEvent(const PushResult(PushOutcome.uploaded));

    expect(
      log.entries.value,
      anyElement(isA<BackupLogEntry>()
          .having((entry) => entry.isFailure, 'isFailure', isFalse)
          .having((entry) => entry.kind, 'kind', 'uploaded')),
      reason: 'after the bad key is removed, a later successful event must '
          'still traverse the controller rather than a poisoned queue dropping it',
    );
  });

  test('back-to-back unserialized events finish with the last event semantics',
      () async {
    // A controller that starts each fold immediately will let the first
    // fault reinsert itself after the last one. A serialized controller holds
    // every later event behind this delayed first persistence.
    SharedPreferences.resetStatic();
    SharedPreferencesStorePlatform.instance = _DelayedFirstLogWriteStore();
    addTearDown(() => SharedPreferences.setMockInitialValues({}));

    controller.handleEventUnserialized(
        _hardFault(BackupFailureKind.offline, operation: 'push'));
    controller.handleEventUnserialized(
        _question(PullOutcome.conflict, _revision('queued-fork')));
    controller.handleEventUnserialized(
        _hardFault(BackupFailureKind.storageFull, operation: 'pull'));

    // dispose waits for the controller's fold queue without adding another
    // event whose semantics could conceal an ordering bug.
    await controller.dispose();

    expect(controller.status.value.state, BackupPillState.failing,
        reason: 'the final queued hard failure must not be overwritten by an '
            'earlier asynchronous fold completing late');
    expect(controller.status.value.activeCondition!.kind,
        BackupFailureKind.storageFull.name,
        reason: 'back-to-back events must be folded in arrival order, not '
            'whichever asynchronous body happens to finish last');
    expect(controller.status.value.activeCondition!.operation, 'pull',
        reason: 'the last event\'s operation must remain attached to the '
            'visible failure so the right recovery action is chosen');
  });

  test('a disabled controller starts grey and exposes no backup controls',
      () async {
    final disabled = BackupController.disabled(now: () => clock);
    addTearDown(disabled.dispose);

    await disabled.start();

    expect(disabled.service, isNull,
        reason: 'the disabled factory must have no target service to contact');
    expect(disabled.canRetry, isFalse,
        reason: 'offering retry without a target would send the operator into '
            'a dead control');
    expect(disabled.status.value.state, BackupPillState.notBackedUp,
        reason: 'without a configured target, starting the app must not imply '
            'that a backup exists or needs review');
    expect(target.revisions, isEmpty,
        reason: 'starting disabled mode must not create or contact a backup '
            'revision');
  });
}
